feat: change version

diff --git a/.github/workflows/build-tag-on-main.yml b/.github/workflows/build-tag-on-main.yml
--- a/.github/workflows/build-tag-on-main.yml
+++ b/.github/workflows/build-tag-on-main.yml
@@ -18,15 +18,19 @@ jobs:
           git fetch --tags
           latest=$(git tag --sort=-v:refname | grep -E '^\d+\.\d+\.\d+$' | head -n 1)
           echo "LATEST_TAG=$latest" >> $GITHUB_ENV
+          echo "LATEST_TAG is $LATEST_TAG"
 
       - name: Get next build number
         id: build
         run: |
+          echo "LATEST_TAG from environment: $LATEST_TAG"
           prefix=$LATEST_TAG
           git fetch --tags
           count=$(git tag --sort=-v:refname | grep -E "^$prefix-[0-9]+$" | wc -l)
           next=$((count + 1))
-          echo "NEW_TAG=$prefix-$next" >> $GITHUB_ENV
+          NEW_TAG="$prefix-$next"
+          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
+          echo "Next build tag will be: $NEW_TAG"
 
       - name: Configure Git User
         run: |
@@ -36,7 +40,13 @@ jobs:
       - name: Create and push new build tag
         run: |
           echo "Creating and pushing tag: $NEW_TAG"
-          
+
+          # Verificar se NEW_TAG está vazio
+          if [ -z "$NEW_TAG" ]; then
+            echo "ERROR: NEW_TAG is empty. Cannot create tag."
+            exit 1
+          fi
+
           # Configurar o token de autenticação para o git
           git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
 
