feat: change version

diff --git a/.github/workflows/build-tag-on-main.yml b/.github/workflows/build-tag-on-main.yml
--- a/.github/workflows/build-tag-on-main.yml
+++ b/.github/workflows/build-tag-on-main.yml
@@ -18,7 +18,7 @@ jobs:
           git fetch --tags
           latest=$(git tag --sort=-v:refname | grep -E '^\d+\.\d+\.\d+$' | head -n 1)
           echo "LATEST_TAG=$latest" >> $GITHUB_ENV
-          echo "LATEST_TAG is $LATEST_TAG"
+          echo "LATEST_TAG=$LATEST_TAG"
 
       - name: Get next build number
         id: build
@@ -32,26 +32,26 @@ jobs:
           echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
           echo "Next build tag will be: $NEW_TAG"
 
-      - name: Configure Git User
-        run: |
-          git config --global user.name "github-actions"
-          git config --global user.email "actions@github.com"
-
-      - name: Create and push new build tag
-        run: |
-          echo "Creating and pushing tag: $NEW_TAG"
-
-          # Verificar se NEW_TAG está vazio
-          if [ -z "$NEW_TAG" ]; then
-            echo "ERROR: NEW_TAG is empty. Cannot create tag."
-            exit 1
-          fi
-
-          # Configurar o token de autenticação para o git
-          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
-
-          # Criar a tag
-          git tag "$NEW_TAG"
-          
-          # Empurrar para o repositório remoto
-          git push origin "$NEW_TAG"
+#      - name: Configure Git User
+#        run: |
+#          git config --global user.name "github-actions"
+#          git config --global user.email "actions@github.com"
+#
+#      - name: Create and push new build tag
+#        run: |
+#          echo "Creating and pushing tag: $NEW_TAG"
+#
+#          # Verificar se NEW_TAG está vazio
+#          if [ -z "$NEW_TAG" ]; then
+#            echo "ERROR: NEW_TAG is empty. Cannot create tag."
+#            exit 1
+#          fi
+#
+#          # Configurar o token de autenticação para o git
+#          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
+#
+#          # Criar a tag
+#          git tag "$NEW_TAG"
+#
+#          # Empurrar para o repositório remoto
+#          git push origin "$NEW_TAG"
